protocol.md
Makes it a bit easier to get the whole picture.
=> add link to JSON-RPC specification

protocol.md
This was broken in 164eb31bd49535dca046034602146f96bb17b56d
=> Fix incorrect numbering in CompletionItemKind

protocol.md
I am suggesting a couple of minor editorial changes regarding spelling, grammar, style, and clarity.
=> Various minor editorial changes

protocol.md
Signed-off-by: Remy Suen <remy.suen@gmail.com>
=> Grammar fixes

contributing.md
"implemenation" should be spelt "implementation".
=> Fix a small typo

protocol.md
Replaced `sent` with `send` as `send` is the infinitive form of the verb.
=> Fix the grammar

specification.md
=> fix Cancelparameters not being displayed right

index.html
Tiny changes to the text in the landing page for better readability.
=> Landing page text polish

_implementors/servers.md
https://github.com/REditorSupport/languageserver
=> add R languageserver

_implementors/servers.md
Adding in a reference to flow-language-server so others can find it more easily.
https://github.com/Microsoft/language-server-protocol/issues/421
=> Add flow-language-server to list

_includes/cookie_notice.html, _includes/head.html, _includes/js_files.html, _layouts/default.html, js/page.js
This has been approved on cookie portal and is good to go.
=> GA and MSCC cookie

_implementors/servers.md
Sorting language servers by Language 😄
=> Sorting language servers by Language

specification.md
This makes it consistent with the rest of the document
=> Separate words `Request Message`

_implementors/servers.md
The project was renamed to Metals, so I updated the name and the repo link.
=> Update Metals link

_implementors/servers.md
I just noticed this while cruising the site.
=> Fix typo in servers.md

_implementors/servers.md
Hope someone else could find this easier.
=> Add wxml-languageserver for wechat miniprograme

_implementors/tools.md
Hello
Here's a quick link to the added project: https://github.com/ul/kak-lsp
Thanks
=> Add Kakoune support to tools.md

_implementors/servers.md
See https://github.com/phan/phan/wiki/Editor-Support
and https://github.com/tysonandre/vscode-php-phan#examples
=> Add Phan to language server list.

_implementors/tools.md
Language client for vim8 and neovim.
=> Add coc.nvim

specification.md
cc https://github.com/Microsoft/vscode-languageserver-node/commit/6c3f8d6891ac651e2b7f9dee4e012fa75be2a5d2, @aeschli
=> Don't require the detail to be copy of name

README.md
Used oxford comma.
As well fixed spelling of "web site"
Closes #560
=> Readme: Use comma to make list more readable

_implementors/servers.md
Nim now has a language server. It's still in the early stages, but it works.
=> Add Nim's language server to the list

_implementors/servers.md
Updates links to the resources of the [ballerina language server](https://github.com/ballerina-platform/ballerina-lang/tree/master/language-server).
=> Update ballerina language server details

_implementors/servers.md
An open source VHDL language server. It currently provides syntax checking and many semantic checks.
=> Add VHDL language server

_implementors/tools.md
Added Sublime Text to tools. Also some formatting and links.
=> Add Sublime Text to tools

_implementors/sdks.md
Add `pygls` -  a pythonic generic language server.
=> Update sdks.md with `pygls` entry

_implementors/servers.md
Adds language servers for D to the implementors list.
=> Add D language servers

_implementors/servers.md
flow-language-server has been deprecated.
for more information: https://github.com/flowtype/flow-language-server/commit/19e42079b05171565050c0f2cbb7597f3d3f5323#diff-04c6e90faac2675aa89e2176d2eec7d8R1
=> Add flow for Javascript Flow

_implementors/servers.md
=> Added implementation language column to servers.md

_implementors/servers.md
Programming language of https://secure.byond.com/
So far supports workspace symbol, definition, type definition, references, hover, completion, signature help.
=> Add DreamMaker language server

_implementors/servers.md
Scripting language for Bethesda Game Studios' Creation Engine.
=> Add Papyrus language server implementation

_implementors/tools.md
[Clout Studio](https://studio.dev.tencent.com/) support LSP for Java/C#/Python/C/C++/TypeScript ans JavaScript , More languages will be supported in the future
=> Add Cloud Studio among the Dev Tools

_implementors/tools.md
See https://github.com/w0rp/ale/issues/2422
=> Add Asynchronous Lint Engine (ALE) tool for vim

indexFormat/specification.md
This applies what I believe was the intention of https://github.com/Microsoft/lsif-node/issues/3
Further changes in `protocol.ts` may be needed.
=> Clarify lazy results

_implementors/servers.md
Now its correct :)
Format of the markdown was incorrect due to one ) instead of ]
=> Correct my typo

_implementors/tools.md
We've recently added internal support in Brackets for LSP. Kindly please add Brackets as an LSP Client here.
@dbaeumer
=> Add Brackets to the list of supporting tools

indexFormat/implementation.md
The section defines benchmark for LSIF (equal to compilation time) and the approach taken by lsif-tsc to compute references efficiently
=> Adds performance section to LSIF guide

_implementors/servers.md
Resolves https://github.com/PowerShell/PowerShellEditorServices/issues/969
=> Update PowerShell LSP implementation to point to server rather than VSIX

_implementors/tools.md
I've recently added LSP support to MS Paint IDE. It's not officially released yet but will be soon, and is available in the codebase.
=> Added MS Paint IDE

specification.md
=> Typos fixes

_implementors/servers.md
It adds [FsAutoComplete](https://github.com/fsharp/FsAutoComplete) to the list
=> Add FsAutoComplete

_implementors/servers.md
My apologies @dbaeumer I did not pay attention and got the the implementation language column wrong.
=> Fixed IBM LSP implementation language

_implementors/sdks.md
=> Add LspCpp to list of SDKs

_implementors/tools.md
add jcide tool to supporting tool list。
=> add jcide tool to list

_specifications/specification-3-15.md
=> Deprecate CompletionItem#deprecated

_implementors/sdks.md
It is still incomplete, currently I'm working on the json parsing.
=> Add WIP C++17 library implementation

_implementors/servers.md
=> Add ActionScript 2.0 entry to servers.md

_specifications/specification-3-15.md
=> Extend TextDocumentPositionParams

_specifications/specification-3-15.md
to be uniform with others typescript snippets
=> Replace ts with typescript in 3.15 markdown

_specifications/specification-3-16.md
Fixes the issue brought up in https://github.com/microsoft/language-server-protocol/commit/5565f27a495129a5fde45d0bdad874dc6f2b404c#r39083581 which was changed from #975
=> Fixes activeParameter description

_implementors/servers.md
Add a language server for Kotlin to the list of LSP implementors.
=> Add Kotlin Language Server

_implementors/servers.md
This PR adds an entry for the WebAssembly language server.
=> Add WebAssembly language server

_implementors/servers.md
update the COBOL language name, adding new language support (HLASM)
=> update Broadcom servers

_data/specification-3-15-toc.yml, _data/specification-3-16-toc.yml
I'm unsure what the process is for updating the website, i.e. which branch should this be PR'd into - so feel free to cherry pick it to anywhere else.
=> website: fix typo (Genernal -> General)

_specifications/specification-3-15.md, _specifications/specification-3-16.md
This addresses the typos noted in #1042.
=> Fix typos in document change notifications

css/main.scss
A warning showed up in the WCP scan that I wasn't able to reproduce running Accessibility Insights locally.
=> Small color tuning for constants

_includes/topnav.html, inspector/index.html
Added a redirect back to overview page for any hard-coded URLs
=> Remote Inspector page until compliance errors fixed

_implementors/servers.md
Very small PR that adds GitHub's CodeQL in the list of language servers
=> Update servers.md to include CodeQL

_implementors/tools.md
https://docs.nova.app/api-reference/language-client/
=> Add Nova to list of Tools supporting the LSP

_specifications/specification-3-16.md
Added missing capabilities for callHierarchy and a missing change for change log.
=> Add missing capabilities for callHierarchy

_specifications/specification-3-16.md
Some changes for LSP 3.16 were missing in the change log. Also, some minor wording fixes.
=> Add some missing items to change log

.vscode/settings.json, _specifications/specification-3-15.md
Also set ruler to 80 characters
=> Tune comment widths to avoid horizontal scroll bar

_specifications/specification-3-16.md
There were still 6 code blocks which triggered horizontal scroll bars on 1920x1080 resolution
=> Tune width of 3-16 spec

_implementors/servers.md
Update new repository for Haskell. Haskell Language Server (HLS).
=> Update for Haskell Language Server (HLS)

_specifications/specification-3-16.md
=> small formatting changes, missing comma

_specifications/specification-3-16.md
=> Clarify window/workDoneProgress/cancel usage

_implementors/servers.md
Corrected URL for VDM server implementation.
=> Correct URL for VDM server implementation

_implementors/servers.md
I made a PowerPC Assembly Language Server a few weeks ago. 
It currently supports syntax highlighting, Go To Definition, Go To Reference, and more.
=> Updated servers.md to include PowerPC Support

_implementors/tools.md
=> add tools list

_specifications/specification-3-16.md, _specifications/specification-3-17.md
Fixed places where there were unnecessary extra spaces or where tabs should have been used instead.
=> Spacing fixes

_specifications/specification-3-16.md, _specifications/specification-3-17.md
This is a collection of minor changes including
- Using semicolons consistently
- Add/Remove spaces
- Fix some variable names in comments
=> Minor changes

_implementors/servers.md
Added REL's language server implementation to the overview page
=> added REL's language server implementation

_implementors/servers.md
LPG-language-server is  a server which  base LSP protocol
=> Add link to LPG-language-server

_specifications/specification-3-16.md, _specifications/specification-3-17.md
=> Clarify how textDocument/selectionRange can handle some missing results

_implementors/tools.md
Add CodeLite IDE to the implementors table
=> Add CodeLite IDE to the implementors table

_implementors/servers.md
This PR updates hyperlinks in Ballerina language server information.
=> Update Ballerina language server links

index.html
https://github.com/microsoft/language-server-protocol/blob/gh-pages/_specifications/specification-3-16.md
Current version is 3.16.
=> The latest version is now 3.16

_implementors/servers.md
Add Bicep language server to implementers table
=> Add Bicep language server to implementers table

_specifications/specification-3-14.md, _specifications/specification-3-15.md, _specifications/specification-3-16.md, _specifications/specification-3-17.md
Fixed a typo in the specifications.
=> Fixed a typo

_implementors/servers.md
Add entry for Ansible language server
=> Add entry for Ansible language server

_implementors/servers.md
Update Ansible docs link and implementation language to typescript
=> Update Ansible language server information

_includes/topnav.html, _layouts/implementors.html, _layouts/specifications.html, index.html
same issues as on DAP site: https://github.com/microsoft/debug-adapter-protocol/pull/217
=> fix a11y issues

css/main.scss
so that they actually align with the text
=> fix the bounding box of `.anchor`s

_implementors/sdks.md
=> Update sdks.md: Add a sdk for golang

_implementors/servers.md
There is no official language server for jsonnet and this is the most complete community one
=> Add jsonnet language server

_implementors/servers.md
[cmake-language-server](https://github.com/regen100/cmake-language-server)
=> Add CMake Language Server

_implementors/servers.md
Add reference to csharp-ls (an alternative language server for C#)
=> Update servers.md, add ref to csharp-ls language server for C#

_implementors/servers.md
Please consider us for inclusion in your list of language servers.  Sigasi is a commercial company building a language server for VHDL & (System)Verilog.
=> Sigasi VHDL / SystemVerilog language server

_implementors/servers.md
Hello, can you add RobotCode language server for RobotFramework?
=> add RobotCode

_implementors/servers.md
=> correct robotcode links
