microsoft/language-server-protocol

protocol.md
I've fixed bunch of typos I noticed while reading through the protocol documentation.
=> Fix typos in protocol.md

protocol.md
See https://github.com/Microsoft/vscode-languageserver-node/blob/032c12a09cf19ad7fb6af997beca1d5f6a7f34b2/server/src/protocol.ts#L411-L416.
The `uri` field is present in the `TextDocumentItem` in any case.
=> DidOpenTextDocumentParams does not extend TextDocumentIdentifier

protocol.md
- consistent use of capital letter after "New:" and "Changed:"
- consistent placing of the colon after New and Changed within the bold section
=> Consistent text style

protocol.md
In previous sections, the suffix 'Notification' and 'Request' was added as suffix in the section header. Added the suffix 'Request' for the section headers where this was missing.
=> Consistent use of suffix 'Request' in headers

protocol.md
* "param" to "params" (both used equally often)
* "export interface" to "interface" (both used equally often)
* added missing "interface" keyword for InitializeResult interface
=> Fixed some non-normative inconsistencies

protocol.md
Clarify semantic of `processId` property of the initialize request.
=> Fixes Microsoft/language-server-protocol#87

README.md
Change link from https://code.visualstudio.com/blogs/ to https://code.visualstudio.com/blogs/2016/06/27/common-language-protocol
=> Link directly to vscode blogpost

protocol.md
The documentation appears to have been copy-pasted from
SignatureInformation and mentioned "signature" when it meant "parameter".
=> Correct minor issue in ParameterInformation doc

protocol.md
resolves #114
The TOC also has icons added to specify if the messages are requests or notifications and in which directions they go. These could also be added to the descriptions.
=> add table of contents to the specification #114

protocol.md
Fix a few typos in the protocol.md file.
Change-Id: Idb67af2a9b0330c07167937eb7f9007287e54d6d
Signed-off-by: othomann <Olivier_Thomann@ca.ibm.com>
=> Fix some typos

protocol.md
In the protocol, interface fields that are meant to specify the URI of a
document are simply declared as `string`. This underspecifies the requirements
of these fields because the contents of the string must be able to parse as a
URI (at a minimum, using the `vscode-uri` npm module).
This introduces a type alias, `DocumentUri`, that tightens these guarantees
without changing the wire protocol. It updates what I believe are all of the
relevant interfaces to specify `DocumentUri` instead of `string`, as
appropriate.
Note that this type is deliberately named `DocumentUri` rather than simply
`Uri` to convey that it is a `URI` that identifies a `TextDocument` in the
LSP object model (as opposed to an arbitrary URI).
I am by no means tied to the name of the type alias: I just want this concept …
=> Introduce DocumentUri concept.

protocol.md
Currently the spec says that `TextDocumentContentChangeEvent.text` contains the new text of the *document*.
I assume that, if the server requested incremental changes and if the client obliged by sending a range+rangelength, then the `text` field merely contains the new text of the *range*.
=> DidChange might only have new text

versions/protocol-1-x.md
Was a duplicate of the show message heading.
=> Correct log message heading in protocol v1

protocol.md
There seems to be an extra "to" in the annotation for the interface `Registration`.
=> Fix typo in summary of `interface Registration`.

protocol.md
=> Fixing 'paramters' and 'reponse' typos

protocol.md
Assuming that it is void, just like for registerCapability.
=> Specify response from client/unregisterCapability

protocol.md
This clarifies what the server is allowed to do in regard to reordering responses to requests, as per the discussion in #306 and https://github.com/freebroccolo/ocaml-language-server/issues/59.
=> Clarify response ordering (#306)

protocol.md
=> Formating is done by server, not by client

protocol.md
The parameters are for the document to format and not to rename.
=> Fix a small typo in protocol.md

_implementors/tools.md
Link to atom-languageclient was incorrect.  (It is an npm package not an apm one - somebody had published something similar on apm which is now deleted)
Fixes #369
=> Correct atom-languageclient link

specification.md
- Fix code block formatting for DocumentLinkParams and ApplyWorkspaceEditResponse
formatting errors can be seen [here](https://microsoft.github.io/language-server-protocol/specification#workspace_applyEdit) and [here](https://microsoft.github.io/language-server-protocol/specification#textDocument_documentLink)
=> Fix code block formatting

_implementors/servers.md
Existing link for OmniSharp server was directing to the node client repo
=> Fix incorrect OmniSharp link

specification.md
A new `CompletionTriggerKind` named `TriggerForIncompleteCompletions` has been added to the vscode-languageserver-node repository in Microsoft/vscode-languageserver-node#308. I have updated the specification so that they can be in sync with each other.
=> Add a new CompletionTriggerKind.TriggerForIncompleteCompletions for re-triggers

_implementors/servers.md
Related issue: https://github.com/Microsoft/vscode-json-languageservice/issues/4
=> Add link to executable version of MS's json server

specification.md
Since the interface is supposed to describe message format to match [JSON-RPC spec](http://www.jsonrpc.org/specification),
the params type must be specified as either `Array` or `Object`.
From spec:
> 4.2 Parameter Structures
>
> If present, parameters for the rpc call MUST be provided as a Structured value. Either by-position through an Array or by-name through an Object.
=> Change message params types to match JSON-RPC spec

specification.md
`workspace/configuration` is a request so it should use a hook instead of an arrow to visually indicate to the reader that something will be sent back to the originator of the message.
=> Change workspace/configuration's icon to be a request

specification.md
`workspace/workspaceFolder` is a request so it should use a hook instead of an arrow to indicate that a response will be sent back to the originator of the message.
=> Change workspace/workspaceFolder's icon to be a request

specification.md
See: https://github.com/Microsoft/language-server-protocol/issues/177
This PR adds a sentence in the specification to specifically note that a server's ability to fulfill a request is independent of whether or not a text document is open or closed.
=> Clarify "textDocument/didOpen" requirement

specification.md
The pipe characters aren't being rendered in HTML. We need to escape them so they'll show up.
=> Escape pipe characters so that they get rendered in HTML

specification.md
a1b13c56810a2617fcfff9c280d4098602a4fb2f didn't include a change to `TextDocumentSyncOptions`. This pull request adds the text to `TextDocumentSyncOptions`'s `change` field also.
=> Fix #447 Clarify the default for TextDocumentSyncOptions's change

specification.md
It's not possible to implement `documentLink/resolve` properly because a `DocumentLink` has no information outside of a non-null `Range` property. Adding a new `data` field to the `DocumentLink` interface will allow information to be transferred and preserved across a `textDocument/documentLink` request and a `documentLink/resolve` request. The server can populate it with whatever it needs on a `textDocument/documentLink` request and then later read it when it later receives a `documentLink/resolve` request.
This fixes #401. See Microsoft/vscode-languageserver-node#336 for the VS Code implementation.
=> Add new data field to DocumentLink to support documentLink/resolve properly

specification.md
It should be possible for completion items and symbols to be flagged as being deprecated. Some editors and IDEs flag such deprecated items by applying a visual affordance such as striking the text out. By introducing this new deprecated property, these editors and IDEs will be able to use its deprecation UI affordance when supporting a language via the LSP.
This implements and closes Microsoft/language-server-protocol#139.
See Microsoft/vscode-languageserver-node#332 for the VS Code implementation.
=> Add deprecated property to CompletionItem and SymbolInformation

specification.md
Unless it's me who doesn't understand the sentence, I think "registering" was meant to be used in these two places, instead of "registered".
=> Fix minor syntax mistakes

_implementors/servers.md
The main repository of language server for Rust has been moved.
=> Change the URL of Rust server

_implementors/servers.md
Prior to this commit the information for the Puppet language server pointed to @jpogran's personal repository, which was accurate.
However, the project has been split out and matured in the Lingua Pupuli namespace. The server, client, and related projects are now grouped there together. The maintainers are Puppet employees.
=> Update Puppet Language Server Info

specification.md
Specification description mentions member "schema", even though examples and typescript spec mention member "scheme".
=> Fix minor typo in specification

contributing.md, versions/protocol-1-x.md, versions/protocol-2-x.md
These were detected by the `misspell` tool
=> Fix typos in contributing.md and protocol-*-x.md

specification.md
This is already returned by the VS Code insiders build and in https://github.com/Microsoft/vscode-languageserver-node/blob/451eee78181d529cfa98ffc7198e2955cdfdc451/protocol/src/protocol.ts#L425.
It seems necessary in order to maintain backwards compatibility with clients that do not yet support the new `DocumentSymbol` type.
=> Add hierarchicalDocumentSymbolSupport to Text Document Client Capabilities

specification.md
See here for the motivation: https://github.com/Microsoft/language-server-protocol/issues/389#issuecomment-407717530
Corresponding vscode-languageclient PR: https://github.com/Microsoft/vscode-languageserver-node/pull/385
=> Add CodeActionOptions with providedCodeActionKinds

_implementors/servers.md
This adds the ReasonML LSP that's being actively developed by wonderful folks like Jared Forsyth and Cheng Lou.
=> Add ReasonML LSP

_implementors/sdks.md
It's not really an SDK but a framework for writing tests against LSP servers
=> Add lsp-test to SDKs

specification.md
The [section for the folding AP](https://microsoft.github.io/language-server-protocol/specification#textDocument_foldingRange) is formatted incorrectly at the moment.
=> Fix formatting for folding API

_data/specification-toc.yml, specification.md
This implements the request from #455.
Introduce a new request for validating whether a rename operation is valid at the given position. The request will also determine whether the range and optionally text to be renamed.
I haven't touched the changelog and protocol versions and so on.
=> Add textDocument/prepareRename

specification.md
This was already changed in most places, but one remains.
=> Fixed textDocument/foldingRanges => textDocument/foldingRange

specification.md
Fixed some typos and noted that `textDocument/prepareRename` is a new 3.12.0 feature.
=> Add version information to the specification

specification.md
For all other requests, the single parameter type is named `...Params`. For consistency, this pattern should also apply to the new folding range request.
=> Renamed FoldingRangeRequestParam => FoldingRangeParams

specification.md
This appears to work inside the local Jekyll server. Happy to edit it if needed.
=> Fixes #461 - Turn headers into hyperlinks (website)

overview.md
The `id` field in JSON-RPC is numeric (matching the type in the request)
=> overview: Fix example response id

_implementors/servers.md
The language server was split out from PTVS a couple months ago.
=> Update MS python-language-server repo

_implementors/servers.md
Apple released it's own implementation of LSP, here I'm suggesting to add it on the list.
=> Add implementation of Swift to LSP list

_implementors/sdks.md
Adding pylspclient - a python implementation of LSP client side. This is still WIP.
=> adding pylspclient for implementations SDKs

specification.md
Not sure if this addition has meaningful consequences, but it seemed missing so here it is.
=> Add Scala language identifier

specification.md
3854f1c503b3e1f1cab9b4f81e62fc47bc7d174a duplicated the `label` property in `ParameterInformation`. Since its type is `string | [number, number]`, I'm assuming the previous one of type `string` can be removed.
=> Remove duplicated label property

_implementors/sdks.md
We've got an open source SDK for Swift LSP clients. It would be great to get it on the list!
=> Add SwiftLSPClient to list of SDKs

_implementors/servers.md
While it lives on the vshaxe org on GitHub, it's essentially maintained by the Haxe Foundation.
=> Update Haxe Language Server info

specification.md
Perl 6 is a different language to Perl 5, with a confusing name.
=> List Perl 5 and Perl 6 identifiers separately

indexFormat/specification.md
This PR updates the number of references for `I#foo()` and `B#foo()` in the example elaborated for `referenceResults`
=> Fix number of references example in LSIF spec

_implementors/servers.md
The analysis server in the Dart SDK now supports LSP natively (see [pkg/analysis_server/tool/lsp_spec](https://github.com/dart-lang/sdk/blob/master/pkg/analysis_server/tool/lsp_spec/README.md)).
=> Add Dart-SDK version of LSP

specification.md
It seems like the `declarationProvider` field was forgotten when updating the protocol to 3.14.0. It exists in the [Microsoft/vscode-languageserver-node repository](https://github.com/Microsoft/vscode-languageserver-node/blob/dbfd37e35953ad0ee14c4eeced8cfbc41697b47e/protocol/src/protocol.declaration.ts#L38-L43) so I don't see why it shouldn't exist here.
This should close #673.
=> Add missing declarationProvider field into server's capabilities

indexFormat/specification.md
This PR changes the key name of contents to comply with what `lsif-typescript` generates. (cc @dbaeumer)
=> Fix contents key name in LSIF spec

indexFormat/specification.md
These changes to project vertex reflect the updated [protocol.ts](https://github.com/Microsoft/lsif-typescript/blob/master/shared/protocol.ts#L289).
=> Update project vertex properties in LSIF spec

indexFormat/implementation.md
This PR introduces a new doc for LSIF implementors, based on feedback from developers working on LSIF. Just like the language server world has a [specification](https://microsoft.github.io/language-server-protocol/specification) and [a guide for language extensions](https://code.visualstudio.com/api/language-extensions/language-server-extension-guide), the idea is to introduce a guide that complements the spec. The goal of this guide is to walk through the developer workflow for building an LSIF exporter.
In this review, I want to bring attention to and get your feedback on:
* The choice of terminology: "LSIF exporter", 2 tools inside the LSIF exporter: "index exporter" (`lsif-tsc`) and "package linker" (`lsif-npm`)
* Details around the rich code navigation scenario (too much/too little?) …
=> Adds LSIF implementation guide

specification.md
Fixes #618.
@dbaeumer I don't know if this is all that's required, or if my description is good enough - but feel free to suggest changes and/or tweak.
(It'd also be good for VS Code to use this too, for example describing a version mismatch if that's the reason it rejects edits).
=> Add optional reason for why the client failed to apply an edit

_implementors/servers.md
Added the language server for kerboscript to the LSP implementations tables. 
This is a side project I've been working on for a programming language, for a mod of a game. The documentation for the kerboscript can be found [here](https://ksp-kos.github.io/KOS/). The main mod / programming language project can be found [here](https://github.com/KSP-KOS/KOS). 
Obviously this is a hyper niche language, and can understand not including to highlight useful languages.
=> Add kerboscript language server to server.md

specification.md
The target URI of a `LocationLink` should be a URI and not just any random string.
=> Fix #758 Change LocationLink's targetUri to be a DocumentUri

specification.md
@dbaeumer I identified some other places with `string` that should be `DocumentUri` instead.
=> Change URI string types to DocumentURIs

_implementors/servers.md
GQL Language server is a language-agnostic LSP implementation for GraphQL. It can be used in polyglot projects across different languages and graphql clients.
=> Add gql-language-server LSP

_implementors/tools.md
We've added LSP support from Spyder 4.0 beta2 onwards.
=> Add Spyder IDE to list of LSP supporting tools

_implementors/servers.md
Add [Terraform-lsp](https://github.com/juliosueiras/terraform-lsp) to list of langserver implementations
=> Add Terraform LSP to list of implementations

_implementors/servers.md
- Drop `dart_language_server` as it is no longer maintained in favor of
the official SDK server.
- Update the owner info for the SDK server to reference the entire team
since it is a fully supported solution.
=> Update Dart server info

_implementors/servers.md
This commit adds [openVALIDATION](https://github.com/openvalidation/openvalidation) to the list.
=> Add openVALIDATION to the list of language server implementations

README.md
The links changed led to 404's either on GitHub or the LSP's website, so I changed them to appropriate working links.
=> Fixed dead links in README

specification.md
Dear Good People at Microsoft LSP,
I found a duplicate field for foldingRangeProvider which I removed. 
I am working on a Go implementation and stumbled on it while defining data structures. This is my first pull request on this project - I did read the contributing guideline and code of conduct, and hopefully I didn't violate either!
Kind regards,
Dayo
=> Removed duplicate foldingRangeProvider field in ServerCapabilities

_specifications/specification-3-14.md
The commit at the head of the gh-pages branch at the time of this writing says "different ... then" instead of "different ... than" inside of a conditional clause.  I have changed "then" to "than" and also made explicit the implicit "then" of the condition, though I am perfectly willing to allow the latter to remain implicit if people prefer that.
=> Correct misuse of "then" where "than" is appropriate.

_specifications/specification-3-14.md
=> Correct a broken link to the canonical copy of a specification.

_specifications/specification-3-15.md
It seems to currently erroneously duplicate `DocumentHighlightClientCapabilities`. Field descriptions taken from 3.14 and `WorkspaceSymbolClientCapabilities`.
=> Fix wrong client capabilities interface listed for document symbol

_implementors/servers.md
I've added to the servers.md page my implementation for an Antlr LSP server. This server provides only basic functionality at the moment: initialize, initialized, open, hover, and goto def. However, the code for much of v3.14 LSP support is currently called in a standard VS IDE 2019 extension. It only needs to be called from the server itself. --Ken Domino
=> Adding Antlr LSP server.

_implementors/tools.md
add Kate text editor, LSP plugin per default integrated since 19.12.0 release
I added it to the back of the table, thought I think somebody should better sort this table somehow.
At the moment that neither looks sorted alphabetically nor for "popularity" (which would be hard to judge, but I would assume e.g. Atom would be more in the top and Kate would stay down ;=)
=> add Kate text editor, LSP plugin per default integrated since 19.12

_implementors/sdks.md
This PR adds a link to a Go SDK for the Language Server protocol. It's currently a work in progress, so I'm hoping publishing a link leads to more contributors and speedy development.\
=> Add WIP Go SDK implementation

_specifications/specification-3-15.md
=> Drop extra foldingRangeProvider definition in 3.15

_specifications/specification-3-15.md
We aready have `export interface ExecuteCommandOptions` (more precise) definition. Let's drop this one to avoid duplication.
=> Drop extra ExecuteCommandOptions def in 3.15

_specifications/specification-3-15.md
interface definition to avoid double definition. We already have the same definition above.
=> Drop duplicated TextDocumentRegistrationOptions

_implementors/servers.md
VsCode Groovy Lint extension repository contains :
- a client
- a server following LSP, so it can be used as Language Server
https://github.com/nvuillam/vscode-groovy-lint/
=> Add Language Server of VsCode Groovy Lint

_specifications/specification-3-15.md
This is documented as being `save` as part of `TextDocumentSyncOptions`. I believe `didSave` here is a typo.
=> make didSave server capability name consistent

_implementors/servers.md
I've added and entry for the suite of three VDM specification languages that we're working on.
=> Update servers.md to include VDMJ-LSP

css/main.scss
Closes #985. I'm pleased to note that sticky table headers are useful in the specification and SDKs page as well. 
Notes on the implementation: the `table.table-responsive { display: block }` from bootstrap prevented sticky table headers from sticking.  I've checked around and I can't notice any adverse effects from moving back to displaying tables as tables, but I'd recommend reviewers check for unexpected side-effects as well.
=> Use sticky table headers

_implementors/servers.md, _implementors/tools.md
RAD Studio, the IDE used for Delphi and C++Builder, has generic LSP v3 support as of version 10.4, released in May 2020. (Previously only the C++Builder personality supported LSP, but C++Builder did not have an entry here.)
Delphi 10.4 also includes a new LSP server for Delphi called DelphiLSP.
More information: https://community.idera.com/developer-tools/b/blog/posts/new-in-delphi-10-4-redesigned-code-insight
=> Add Delphi and C++Builder support

_implementors/servers.md
The language server at https://github.com/CodeChain-io/solidity-language-server
does not exist any more.
=> Remove now non-existent solidity language server

_specifications/specification-3-15.md, _specifications/specification-3-16.md
Hi ! This is a follow-up on #943 
This is just a draft since :
=> Specify logTrace notification 

_specifications/specification-3-16.md
These little inconsistencies tripped up the code I'm using to parse the blocks out of this code to generate types (slightly related to #67).
=> Minor tweaks for consistency to improve parsing

_implementors/servers.md
Sysl (pronounced "sizzle") is a open source system specification language. The repository contains an implementation of its LSP.
=> Add reference to Sysl LSP

_implementors/servers.md
hey there!
just updating the entry for `graphql-language-service-server`, which has been merged into a larger monorepo, and is now an official project of the graphql foundation. 
it is used by the second most popular graphql language extension for vscode, as well as the most popular graphql completion for vim! we are almost feature complete, just need references/implementations. 
thanks for such an excellent protocol and implementation via `vscode-languageservice`!
=> update official graphql implementation entry

_specifications/specification-3-16.md
These fields were documented, but not included in this definition. This prevented them showing up in the code I'm generating from the spec.
=> Add capabilities fields for semantic tokens

_specifications/specification-3-16.md
Fixes minor typo in the semantic tokens section in v3.16 specification.
Signed-off-by: hasheddan <georgedanielmangum@gmail.com>
=> Fix typo in v3.16 semantic tokens section

css/main.scss, index.html
Fix typo in alt text.
Also tune more code block items after checking LSIF specification examples.
=> Fix typo and LSIF code block color contrast

_implementors/servers.md
Noticed the link was broken for lsp4xml. lsp4xml was moved to eclipse and renamed to LemMinX.
FYI @angelozerr
=> Fix XML (LemMinX) implementation link

_implementors/servers.md
The Elixir LS project has been forked and the previous project has been discontinued. This updates the document to point to the current projec.t
=> Update ElixirLS to currently maintained project

_implementors/sdks.md
I am adding here my LspTypes C# library, which implements every message parameter type in the 3.16 spec and works with VS2019, VSCode, Emacs lsp-emacs with my server [Antlrvsix](https://github.com/kaby76/AntlrVSIX). Other versions will be scraped directly from the online spec with a tool I will be writing because it took me a week to methodically hand-translate the spec into C#.
I cleaned up the table slightly by sorting it by the first column, which was done in the [servers table](https://microsoft.github.io/language-server-protocol/implementors/servers/). However, the link for "C# | MS | work in progress by David Wilson" is completely useless for people looking for resources to *actually implement code*. I suggest this row be deleted, or MS actually open-source whatever library that is …
=> Add LspTypes for C# and clean up table.

_includes/cookie_notice.html, _includes/footer.html, _includes/head.html, _includes/js_files.html, inspector/index.html, js/page.js
The only cookie currently is the GA essential cookie so we don't need to do any conditional creation or disabling.
This PR just updates the cookie banner and adds the "Manage cookies" link to the footer.
=> Update to new Microsoft cookie banner

_specifications/specification-3-16.md
Pairwise dollar signs on the same line are misinterpreted as math delimiters if they are not escaped.
=> Escape dollar signs.

_specifications/specification-3-16.md
- Added `window.showDocument` and `general.regularExpressions` to `ClientCapabilities`.
- Fix spelling of `RegularExpressionsClientCapabilities`.
=> Added missing client capabilities and fixed misspelling

_specifications/specification-3-16.md
This improves some wording, mainly for newly added text. That includes grammar and spelling fixes.
@dbaeumer Many of these would be (and were) found with a simple spell checker. Would you be willing to use one of those? I use and recommend [Code Spell Checker](https://marketplace.visualstudio.com/items?itemName=streetsidesoftware.code-spell-checker).
=> Improve wording

_specifications/specification-3-16.md
Made the names consistent with the naming convention used for other interfaces.
=> Fix trace param interface names

_specifications/specification-3-16.md
@dbaeumer would you accept these tweaks to improve parsing the spec? One of the definitions uses `URI` as a type, but it's not defined in code anywhere. My understanding is that it's a string (same as `DocumentUri`).
The other change makes the type of a *response* a single block of code, so it can be more easily identified. Multiple code blocks is a little more tricky to parse and I don't think anything is lost doing it this way.
=> Tweaks to simplify parsing of spec

_specifications/specification-3-16.md
@dbaeumer this is a first go at  #984 using `WaitUntil` requests. It currently only includes rename, but we can duplicate for create/delete once these are good if required.
Some things I wasn't sure about:
- Should the capabilities just be bools, or additional nested objects for easier extending in future (or would they just be changed to `boolean | {/*...*/}`?
- Is `workspace` the right place for these? Save etc. are in `textDocument/` but these could be folder renames so there's no specific document.
- Is it valid to have no registration options? Servers should be able to opt in/out, but otherwise I don't think there's anything (I don't think using document selectors would make sense as it may force the client to scan down the whole tree for folder renames).
- Is v3.16.0 correct or may …
=> Add window/{did,will}{Create,Rename,Delete}Files

_implementors/sdks.md
I added an entry to the `SDKs for the LSP` page a long time ago with my attempt at an LSP SDK written in Go. Unfortunately I haven't had much time to implement it, so I thought it'd be a good idea to remove it from the list as to not mislead anybody.
Cheers!
=> Remove Go SDK

_specifications/specification-3-16.md
@dbaeumer spotted this when re-generating my classes. This was added in both https://github.com/microsoft/language-server-protocol/pull/1156 and bae2aaba5946c84cb28c28f4437711d744576ed7 so there were two. This removes the one added in my PR and leaves just yours.
=> Remove duplicate URI definition

_specifications/specification-3-15.md, _specifications/specification-3-16.md, _specifications/specification-3-17.md
Incorrect:
https://microsoft.github.io/language-server-protocol/specification#textedit
Correct:
https://microsoft.github.io/language-server-protocol/specification#textEdit
Also added missing parenthesis in some old version of the spec.
=> Fix case of textEdit link

_implementors/servers.md
Adds the racket-langserver language server for Racket to the list.
You can find the project here: https://github.com/jeapostrophe/racket-langserver.
=> Add racket lang server to list of servers

_specifications/specification-3-15.md, _specifications/specification-3-16.md, _specifications/specification-3-17.md
This will make notation more consistent, update some copy/paste mistakes and fix a typo.
=> Patch up the docs

_implementors/sdks.md
LXTK is an open source toolkit for implementing language clients
talking to language servers according to the LSP.
=> Add LXTK to SDKs

_specifications/specification-3-17.md
This looked like an error - the field is in `completionItem` in the definition.
=> Fix reference to insertReplaceSupport capability

_implementors/servers.md
* As far as I know, Crystalline works fine on newer Crystal versions even in Scry is not working
* Crystalline has been added to `awesome-crystal` as https://github.com/veelenga/awesome-crystal/pull/545
* I have updated VSCode extension Wiki as https://github.com/crystal-lang-tools/vscode-crystal-lang/wiki/Settings/_compare/9d305efc7b12230272e574e9ef008759c55beba4...b7e0500c1f67c90640b4d7eef28afad90c7be6b4 
* Scry repository looks moved to https://github.com/crystal-lang-tools/scry
* Documents describes `Scry`, it is correct naming rather than `scry`
@elbywan I believe Crystalline is the great tool for Crystal users. Thanks for the project 🙏
=> Update Crystal LSP implementations

_specifications/specification-3-16.md
Replace "completion item" with "symbol" for `tags` field description.
=> Fix typo in LSP 3.16

_implementors/servers.md
Current links in clangd row are 404. Website and source for clangd were moved:
- website: https://clangd.llvm.org/
- source: https://github.com/llvm/llvm-project/tree/main/clang-tools-extra/clangd (LLVM moved their sources from own SVN server to GitHub)
=> Fix links to clangd

_implementors/servers.md
Add the Smalltalk/Pharo language server into the list of the existing server implementation.
> One of the corresponding client for VSCode is here: https://marketplace.visualstudio.com/items?itemName=badetitou.pharo-language-server
=> Add Pharo Smalltalk Language Server

_specifications/specification-3-16.md, _specifications/specification-3-17.md
I introduced that mismatch when specifying the behaviour of setTrace apparently, see [this diff].(https://github.com/microsoft/language-server-protocol/pull/953/files)
'messages' is still the one being used by VSCode, and it has been an issue for [ocaml-lsp](https://github.com/ocaml/ocaml-lsp/pull/425)
the standard implementation still uses 'messages' as it was before that change
=> 'message' to 'messages' in TraceValue

_implementors/servers.md
[sqls](https://github.com/lighttiger2505/sqls) is an under-development MySQL/PostgreSQL/SQLite LSP written in Go by [lighttiger2505](https://github.com/lighttiger2505).
=> Add sqls to list of LSP implementations.

_specifications/specification-3-16.md, _specifications/specification-3-17.md
=> Fix missing semicolon in specification 3.16 and 3.17

_implementors/servers.md
I'd like to add the LanguageTool language server [ltex-ls](https://github.com/valentjn/ltex-ls) (maintained by me) to the list of language servers on the website. It's a fork of Adam Voss's language server, which is already in the list but which is unmaintained since 2017 due to the passing of its author. It should be significant enough as there are language clients for VS Code (&ldquo;reference client&rdquo; [vscode-ltex](https://github.com/valentjn/vscode-ltex), also maintained by me), Sublime Text, Emacs, and Neovim. Server and reference client have a pretty extensive [documentation](https://valentjn.github.io/vscode-ltex/docs/settings.html) of the configuration.
=> Add ltex-ls to list of language servers

_specifications/specification-3-14.md, _specifications/specification-3-15.md, _specifications/specification-3-16.md, _specifications/specification-3-17.md
- When playing around with isIncomplete it was unclear from the spec perspective on the appropriate handling of isIncomplete. Clarifying that isIncomplete should represent "replaced" items and not "appended" items makes it clear how a language server should handle the feature.
- Ported the wording to all previous specs + fixed some typos.
=> Clarify isIncomplete feature behavior.

_specifications/specification-3-16.md, _specifications/specification-3-17.md
Used as backend in https://facelessuser.github.io/sublime-markdown-popups
which is used as backend in https://lsp.sublimetext.io
=> Add Python-Markdown to the known markdown parsers of clients

_specifications/specification-3-17.md
See: https://spec.commonmark.org/0.29/#example-131
=> Fix: missing empty lines between html end tags and start of code blocks

_implementors/sdks.md, _implementors/servers.md
- Added [Langium](https://github.com/langium/langium), a new language server SDK written in TypeScript
- Moved Xtext from _Language Servers_ to _SDKs_ and added link to project committers
- Added link to LSP4J project committers
=> SDKs: Added Langium, moved Xtext

_specifications/specification-3-17.md
@dbaeumer I don't know if this is reasonable, but VS Code has a constant for it and it seems like it would be useful for the same reason as having `source.organizeImports` here - so clients can provide better UI beyond just the Source Actions list for invoking this kind of (common) operation.
=> Add source.fixAll constant

_specifications/specification-3-16.md, _specifications/specification-3-17.md
Updates "to easy" to "to ease" in implementation section of the 3.16 and
3.17 specifications.
Signed-off-by: hasheddan <georgedanielmangum@gmail.com>
=> Fix minor typos in 3.16 and 3.17 specifications

_specifications/specification-3-16.md
The comment states that it is the start of the range, but the variable name states it is the end. The variable name seems to be correct, so update the comment.
=> Update comment for jsonrpcReservedErrorRangeEnd

_implementors/servers.md
The first column of the language server table is the Language, and it is mostly alphabetically sorted. A year or more ago, last time I checked this list, it was fully alphabetically sorted by the language name. However today there are a few entries that were not placed in the table following that precedent, and this makes it confusing to read or scan the table. This moves those confusing items so the table is once again alphabetically sorted by language.
I have moved:
* Deno to between Delphi and Dockerfiles
* The IBM servers for High Level Assembler to A for Assembler (see note below)
* The IBM servers for COBOL to C, for COBOL
* Crane PHP to PHP
* JSON to the end of the J section
* T-SQL from between R and S, to T. This is because T-SQL is not quite the same as SQL [according to …
=> Adjusted alphabetical sorting by language

_implementors/servers.md
Hi,
The IBM Z Open Editor VSCode extension contains an IBM TSO/E REXX LSP implementation. We love the specification!
Thanks,
Bradley Knaysi
Software Developer, IBM
=> Add implementor for IBM TSO/E REXX LSP server

_implementors/tools.md
That makes it arguably easier to scan the table visually.
I also changed the two entries labelled `emacs` resp. `GNU Emacs` to both say `Emacs`
(an alternative would be to leave them as `GNU Emacs` but sort them under `Emacs`).
There are some more entries one may argue about, e.g. should "GNOME Builder" be sorted
under "G" or "B"? What about "MS Monaco"?
Finally, one entry says "Multiple editors"; the underlying ycmd tool supports Emacs,
vim, atom, sublime, geany, kakoune, nano, ... perhaps it should be listed multiple times?
=> Sort list of supporting tools alphabetically

_implementors/servers.md
This LSP implementation at hand is a bit unusual in that it does not natively parse and understand the source code but instead,
- compiles it to JavaScript
- feeds the JS to tsserver
- maps back TS response using source maps
---
This principle can also be applied to other [languages that compile to JavaScript](https://github.com/jashkenas/coffeescript/wiki/List-of-languages-that-compile-to-JS) (there are many), given they are somewhat relevant, don't have a lsp impl or type checks yet and also emit source maps (not so many). Matching this criteria are:
- [LiveScript](https://livescript.net/)
- [IcedCoffeeScript](http://maxtaco.github.io/coffee-script)
- [Sibilant](https://github.com/jbr/sibilant)
- [LiteScript](https://github.com/luciotato/LiteScript)
- …
=> Add CoffeeSense (CoffeeScript LSP)

_specifications/specification-3-16.md
Relates to https://github.com/microsoft/language-server-protocol/issues/1170#issuecomment-754675111.
There are still some questions about multiline tokens, but I think it makes sense to clarify this in the meantime.
=> Clarify lengths that go past the end of the line for single-line semantic tokens

_specifications/specification-3-16.md
Some minor type fixes that did help my automatic parsing of the specification to generate a c++ implementation of LSP:
* always use "_Client Capability_:" before client capabilities
* correct typo putting colon before_
* always add colon after "* property type"
=> Make specification more uniform to improve automatic parsing

_includes/js_files.html
- I tried making linking >= 3-17; however, that wasn't easily doable due to the structure of the jekyll site. The JSFiles themselves are included in the layout which don't have access to page level information. Because of this I've hacked a hardcoded "if 3.17" check into the injected JavaScript to support linking. Once we publish 3.17 we'll need to go back and update the logic to ensure that 3.17+ is supported.
Originally attempted fix here: https://github.com/microsoft/language-server-protocol/pull/1342
=> Restrict linking to only the 3-17 specification.

_implementors/servers.md
The original URL (OmniSharp/csharp-language-server-protocol)
is an SDK and is already listed in sdks.md.
=> The C# LSP is in OmniSharp/omnisharp-roslyn.

_implementors/servers.md
Added `fortls` Language Server for Fortran, which started as a fork of the `fortran-language-server` (which appears to be unmaintained for the past 2y).
`fortls` since its original creation has diverged substantially from its upstream so I think it is reasonable for it to be included as a separate entry.
=> Added `fortls` Fortran LS

_specifications/specification-3-14.md, _specifications/specification-3-16.md, _specifications/specification-3-17.md
`language id`(lower case) is used in all the SPEC, but there is only one `language Id`(upper case for `I`).
it is not consistent, and also may lead to confusion between `l(lower case L)` and `I(upper case i)`, the [SPEC page](https://microsoft.github.io/language-server-protocol/specifications/specification-current/#textDocument_didOpen), for example:
=> use language id for consistence

_implementors/tools.md
Neovim has had native LSP-support since version 0.5.
Previously, it was only listed in the context of Vim/Neovim plugins.
=> Add Neovim to supporting tools

css/main.scss
This PR adds more CSS rules to fix some outline shapes to look more rectangular.
Ref https://github.com/microsoft/debug-adapter-protocol/issues/252
An example of the new outline:
=> Add padding to more links

_specifications/lsp/3.17/specification.md
The URL scheme is different for 3.17
=> Update specification URL for pull requests

_specifications/lsp/3.17/general/initialize.md
`workspace.inlineValue` is defined in spec but missing from `ClientCapabilities`.
=> Add `workspace.inlineValue` to capabilities

_specifications/lsp/3.17/language/foldingRange.md
This proposes an additional property on foldingRange that allows a server to specify what text should be shown by the client when text is folded. 
#1426
=> Add collapsedText to foldingRange

_specifications/lsp/3.17/language/foldingRange.md
Enforce using the enum for `kind`.
=> Use FoldingRangeKind for kind

_implementors/tools.md
lsp-bridge's goal is to become the fastest LSP client in the Emacs.
lsp-bridge use python threading technology build cache bridge between Emacs and LSP server, you will never feel stuck when you write the code.
=> Add lsp-bridge, lsp-bridge is LSP client for Emacs
